/**
 * The version check, attacked rather than demonstrated.
 *
 * **Against a real Postgres, not PGlite.** What is under test is a
 * transaction, a conditional `UPDATE ... WHERE version = $n` and the row count
 * it returns - the three things a substitute engine is most likely to be
 * subtly generous about. The rest of the suite can be hermetic; this one
 * cannot be, and `compose.dev.yaml` is what it runs against.
 *
 * Skips rather than fails when no database is reachable, because a green run
 * that silently proved nothing is worse than an obvious skip.
 */
import { eq } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/node-postgres'
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest'

import { updateVersioned } from './mutate.js'
import { cases, changeFeed, user } from './schema/index.js'
import { openTestPool } from '../../test/database.js'

const URL_ = process.env.DATABASE_URL ?? ''
const pool = URL_ ? openTestPool(URL_, 'ic_app') : null
const db = pool ? drizzle({ client: pool }) : null

/**
 * The handle fixtures arrange rows through.
 *
 * **`ic_seed`, because a fixture writes across cases and the app role may
 * not.** Row-level security refuses an unscoped write, so a fixture on the
 * app handle fails before the test it was arranging ever runs. The subject
 * under test keeps `db` - if it forgets to scope itself, it fails here.
 */
const seedPool = process.env.SEED_DATABASE_URL
  ? openTestPool(process.env.SEED_DATABASE_URL, 'ic_seed')
  : pool
const seed = seedPool ? drizzle({ client: seedPool }) : null

const ANALYST_A = 'test-analyst-a'
const ANALYST_B = 'test-analyst-b'

/** Generated by the database now, so it is captured per test rather than fixed. */
let CASE_ID: string

describe.skipIf(!db)('a version-checked write', () => {
  beforeAll(async () => {
    await seed!.insert(user).values(
      [ANALYST_A, ANALYST_B].map((id) => ({
        id,
        name: id,
        email: `${id}@example.test`,
        emailVerified: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      })),
    )
  })

  afterAll(async () => {
    await seed!.delete(changeFeed)
    await seed!.delete(cases)
    await seed!.delete(user).where(eq(user.id, ANALYST_A))
    await seed!.delete(user).where(eq(user.id, ANALYST_B))
    await pool!.end()
  })

  beforeEach(async () => {
    await seed!.delete(changeFeed)
    await seed!.delete(cases)
    const [row] = await seed!
      .insert(cases)
      .values({ title: 'Phishing wave', createdBy: ANALYST_A, updatedBy: ANALYST_A })
      .returning({ id: cases.id })
    CASE_ID = row!.id
  })

  it('refuses the second of two writes made from the same read', async () => {
    // The defect this whole design exists to prevent: both analysts read
    // version 1, and without the check the second silently overwrites the
    // first with no trace that anything was lost.
    const first = await updateVersioned(db!, {
      table: cases,
      entity: 'cases',
      caseId: CASE_ID,
      id: CASE_ID,
      expectedVersion: 1,
      actorId: ANALYST_A,
      patch: { title: 'Phishing wave \u2014 confirmed' },
    })
    const second = await updateVersioned(db!, {
      table: cases,
      entity: 'cases',
      caseId: CASE_ID,
      id: CASE_ID,
      expectedVersion: 1,
      actorId: ANALYST_B,
      patch: { title: 'Phishing wave \u2014 false positive' },
    })

    expect(first.ok).toBe(true)
    expect(second.ok).toBe(false)

    // The refusal has to name where the row got to, or the merge review has
    // nothing to show the analyst who lost.
    expect(second.ok === false && second.currentVersion).toBe(2)

    const [row] = await seed!.select().from(cases).where(eq(cases.id, CASE_ID))
    expect(row!.title).toBe('Phishing wave \u2014 confirmed')
    expect(row!.updatedBy).toBe(ANALYST_A)
  })

  it('writes exactly one change-feed row for one accepted write', async () => {
    // A refused write that still announced itself would repaint every other
    // screen with a change that never happened.
    await updateVersioned(db!, {
      table: cases,
      entity: 'cases',
      caseId: CASE_ID,
      id: CASE_ID,
      expectedVersion: 1,
      actorId: ANALYST_A,
      patch: { status: 'closed' },
    })
    await updateVersioned(db!, {
      table: cases,
      entity: 'cases',
      caseId: CASE_ID,
      id: CASE_ID,
      expectedVersion: 1,
      actorId: ANALYST_B,
      patch: { status: 'open' },
    })

    const feed = await seed!.select().from(changeFeed)
    expect(feed).toHaveLength(1)
    expect(feed[0]!.fields).toEqual(['status'])
    expect(feed[0]!.actorId).toBe(ANALYST_A)
    expect(feed[0]!.version).toBe(2)
  })

  it('advances the version by exactly one per accepted write', async () => {
    // **Renamed after a break-verify said the old name was a lie.** It was
    // "increments in SQL, so two writers cannot compute the same next
    // version" - and replacing the SQL increment with `expectedVersion + 1`
    // leaves this green, because the `where` guarantees those are the same
    // number. The SQL form is defensive, not the mechanism.
    //
    // What it does hold: no write skips a version and none double-increments,
    // so a client's next `expectedVersion` is always the one it just received.
    for (const [i, actor] of [ANALYST_A, ANALYST_B, ANALYST_A].entries()) {
      const result = await updateVersioned(db!, {
        table: cases,
        entity: 'cases',
        caseId: CASE_ID,
        id: CASE_ID,
        expectedVersion: i + 1,
        actorId: actor,
        patch: { summary: `pass ${i}` },
      })
      expect(result.ok).toBe(true)
    }
    const [row] = await seed!.select().from(cases).where(eq(cases.id, CASE_ID))
    expect(row!.version).toBe(4)
  })

  it('reports a missing row as refused rather than throwing', async () => {
    // A row deleted by another analyst mid-edit is the same answer as one
    // written by them: this save cannot proceed. `null` distinguishes gone
    // from moved, which is what the merge review needs to word it.
    const result = await updateVersioned(db!, {
      table: cases,
      entity: 'cases',
      caseId: CASE_ID,
      id: '00000000-0000-0000-0000-000000000000',
      expectedVersion: 1,
      actorId: ANALYST_A,
      patch: { title: 'x' },
    })
    expect(result.ok).toBe(false)
    expect(result.ok === false && result.currentVersion).toBeNull()
  })
})
