/**
 * The Dutch pack, for the keys it could be carried across for.
 *
 * Partial by design: a key with no entry here falls back to the English pack,
 * so a Dutch report is visibly part English rather than silently so. Adding one
 * needs a Dutch speaker, never a script. -> `labels.en.ts`, which is the schema
 */

export const NL: Record<string, string> = {
  'column.account': 'Account',
  'column.actor': 'Actor',
  'column.asset': 'Asset',
  'column.assignee': 'Behandelaar',
  'column.disposition': 'Afhandeling',
  'column.assurance': 'Zekerheid \u00b7 bron',
  'column.domain': 'Domein',
  'column.due': 'Uiterste datum',
  'column.event': 'Gebeurtenis',
  'column.events': 'Gebeurtenissen',
  'column.evidence': 'Bewijsmateriaal',
  'column.method_ref': 'Ref',
  'column.established': 'Wat dit heeft vastgesteld',
  'column.where_and_window': 'Waar het draaide, en waarover',
  'column.rows_returned': 'Rijen',
  'column.indicator': 'Indicator',
  'column.malware': 'Bestand',
  'column.metric': 'Metriek',
  'column.port': 'Poort',
  'column.publisher': 'Uitgever',
  'column.tactic': 'Tactiek',
  'column.task': 'Taak',
  'column.term': 'Term',
  'column.type': 'Type',
  'column.value': 'Waarde',
  'column.verdict': 'Oordeel',
  'column.zone': 'Zone',
  'empty.accounts': 'Geen accounts vastgelegd.',
  'empty.actions': 'Geen responsacties vastgelegd.',
  'empty.assets': 'Geen assets vastgelegd.',
  'empty.evidence': 'Geen bewijsmateriaal vastgelegd.',
  'empty.methods': 'Geen methoden vastgelegd.',
  'empty.indicators': 'Geen netwerkindicatoren vastgelegd.',
  'empty.malware': 'Geen malware vastgelegd.',
  'empty.timeline': 'Geen tijdlijnregels vastgelegd.',

  'figure.unplaced': 'Geen afbeelding gekozen voor deze figuur.',
  'figure.missing': 'Het bewijsrecord voor deze figuur zit niet meer in de zaak.',
  'figure.unavailable': 'Deze installatie heeft de afbeelding voor dit record niet.',
  'field.analyst': 'Analist',
  'field.console': 'Console',
  'field.workspace': 'Werkruimte',
  'field.run_by': 'Uitgevoerd door',
  'field.run_at': 'Uitgevoerd op',
  'field.case_id': 'Casus',
  'field.closed': 'Gesloten',
  'field.contained': 'Ingedamd',
  'field.customer': 'Klant',
  'field.detected': 'Gedetecteerd',
  'field.detection_source': 'Detectiebron',
  'field.eradicated': 'Verwijderd',
  'field.incident_class': 'Incidentklasse',
  'field.opened': 'Geopend',
  'field.recovered': 'Hersteld',
  'field.severity': 'Ernst',
  // **The sections an analyst writes under.** The pack carried headings for
  // the generated sections only, so a Dutch report titled every written
  // section in English -- and the language control changed nothing an analyst
  // could see, which is what it was reported as.
  'heading.analysis': 'Analyse',
  'heading.analyst_notes': 'Notities van de analist',
  'heading.cross_border_impact': 'Grensoverschrijdende impact',
  'heading.exec_card': 'Samenvatting',

  // The generated sections. Written to match the register the rest of this
  // pack uses; a native reader should still check them, and the untranslated
  // list above is the place a correction shows up.
  'heading.case_header': 'Casus',
  'heading.metrics': 'Responsstatistieken',
  'heading.timeline': 'Tijdlijn van gebeurtenissen',
  'heading.entities': 'Systemen, accounts en indicatoren',
  'heading.ribbon': 'Verloop van de aanval',
  'heading.glossary': 'Gebruikte begrippen',
  'heading.evidence': 'Bewijsmateriaal',
  'heading.methods': 'Methoden',
  'heading.actions': 'Responsmaatregelen',
  'heading.impact': 'Impact',
  'heading.techniques': 'Technieken en subtechnieken',
  'heading.technique_table': 'Waargenomen technieken',
  'heading.indicators': 'Indicatoren van compromittering',
  'heading.exec_summary': 'Managementsamenvatting',
  'heading.initial_assessment': 'Eerste beoordeling',
  'heading.killchain': 'Kill chain-dekking',
  'heading.narrative': 'Incidentverslag',
  'heading.figure': 'Figuur',
  'heading.recommendations': 'Aanbevelingen',
  'heading.root_cause': 'Grondoorzaak',
  'heading.status_update': 'Statusupdate',
  'heading.what_happened': 'Wat er is gebeurd',
  'heading.what_is_still_open': 'Wat nog openstaat',
  'heading.what_we_did': 'Wat wij hebben gedaan',
  'heading.what_we_recommend': 'Wat wij aanbevelen',
  'impact.assets_compromised': 'Gecompromitteerde assets',
  'impact.indicators_malicious': 'Kwaadaardige indicatoren',
  'impact.severity': 'Ernst',
  'report.title': 'Incidentrapport',
  'cover.classification': 'Classificatie',
  'metric.case_age': 'Looptijd van de casus',
  'metric.containment_coverage': 'Dekking van de indamming',
  'metric.dwell': 'Verblijfsduur',
  'metric.time_to_detect': 'Tijd tot detectie',
  'narrative.adversary': 'Activiteit van de aanvaller',
  'narrative.our_action': 'Onze actie',
  'ribbon.phases_reached': 'Bereikte fasen',
  'rootcause.threat_action': 'Dreigingsactie',
  'value.no': 'Nee',
  'value.not_recorded': 'Niet vastgelegd',
  'value.not_stated': 'Niet opgegeven',
  'value.rows_as_recorded': '{n} rijen teruggegeven, zoals vastgelegd door de analist',
  'value.rows_not_stated': 'Aantal rijen niet opgegeven',
  'value.of': 'van',
  'value.ongoing': 'lopend',
  'value.adversary': 'Aanvaller',
  'value.response': 'Onze respons',
  'value.yes': 'Ja',
}
