/*
 * The NIS2 Implementing Regulation's published thresholds.
 *
 * GENERATED by .claude/scripts/lift_nis2_thresholds.py. Do not edit.
 *
 * Commission Implementing Regulation (EU) 2024/2690. Every figure is checked
 * against the vendored Official Journal text by `compliance/oj.test.ts`, which
 * is the only thing that can catch a mistranscribed limb: a wrong figure
 * computes perfectly. Regenerate rather than editing.
 *
 * `LIMITED_AVAILABILITY` is `[minutes, share, absolute]` and a **`null` means
 * the article has no such limb**, never a limit of zero: adding a half the
 * article does not contain over-reports, and requiring one it does not contain
 * under-reports. `COMPLETE_OUTAGE_MINUTES` of `0` means any complete outage
 * counts at all.
 */

/** Entity types the IR covers, keyed to the article setting their criteria. */
export const IR_ARTICLES: Record<string, string> = {
  cdn: 'IR Art 9',
  cloud: 'IR Art 7',
  datacentre: 'IR Art 8',
  dns: 'IR Art 5',
  marketplace: 'IR Art 11',
  msp: 'IR Art 10',
  mssp: 'IR Art 10',
  search: 'IR Art 12',
  social: 'IR Art 13',
  tld: 'IR Art 6',
  trust: 'IR Art 14',
}

/** IR Art 3(1)(a): EUR 500 000 **or** 5% of turnover, whichever is lower. */
export const GENERAL_LOSS_EUR = 500000
export const GENERAL_LOSS_TURNOVER_SHARE = 0.05

/** Minutes of *complete* unavailability. `0` means any complete outage counts. */
export const COMPLETE_OUTAGE_MINUTES: Record<string, number> = {
  cdn: 30,
  cloud: 30,
  datacentre: 0,
  dns: 30,
  msp: 30,
  mssp: 30,
  tld: 0,
  trust: 20,
}

/** `[minutes, share, absolute]`; `null` means the article has no such half. */
export const LIMITED_AVAILABILITY: Record<string, [number | null, number | null, number | null]> = {
  cdn: [60, 0.05, 1000000],
  cloud: [60, 0.05, 1000000],
  datacentre: [60, null, null],
  msp: [60, 0.05, 1000000],
  mssp: [60, 0.05, 1000000],
  trust: [null, 0.01, 200000],
}

/** The three types whose only availability test is how many users were reached. */
export const USER_SHARE_ONLY: Record<string, [number, number]> = {
  marketplace: [0.05, 1000000],
  search: [0.05, 1000000],
  social: [0.05, 1000000],
}

/** Limbs Articles 5-14 need that the case stores no field for. */
export const UNSTORED_LIMBS: Record<string, string[]> = {
  cdn: ['integrity of stored or processed data (Art 9(c), 9(d))'],
  cloud: ['integrity of stored or processed data (Art 7(c), 7(d))'],
  datacentre: [
    'integrity of stored or processed data (Art 8(c))',
    'physical access to the data centre (Art 8(d))',
  ],
  dns: [
    'resolution time above 10 seconds for more than an hour (Art 5(b))',
    'integrity of authoritative resolution data (Art 5(c))',
  ],
  marketplace: ['integrity of stored or processed data (Art 11(c), 11(d))'],
  msp: ['integrity of stored or processed data (Art 10(c), 10(d))'],
  mssp: ['integrity of stored or processed data (Art 10(c), 10(d))'],
  search: ['integrity of stored or processed data (Art 12(c), 12(d))'],
  social: ['integrity of stored or processed data (Art 13(c), 13(d))'],
  tld: [
    'resolution time above 10 seconds for more than an hour (Art 6(b))',
    'integrity of data for the technical operation of the TLD (Art 6(c))',
  ],
  trust: [
    'more than an hour of unavailability per calendar week (Art 14(b))',
    'physical access to restricted areas (Art 14(d))',
    'integrity loss above 0,1% of users or 100 users (Art 14(e))',
  ],
}
